ALTER TABLE video_views
  ADD COLUMN referrer TEXT NOT NULL DEFAULT '',
  ADD COLUMN browser TEXT NOT NULL DEFAULT '',
  ADD COLUMN device TEXT NOT NULL DEFAULT '',
  ADD COLUMN country TEXT NOT NULL DEFAULT '',
  ADD COLUMN city TEXT NOT NULL DEFAULT '';
