name: Feature Request
description: Suggest a feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve? What are you trying to do?
      placeholder: I need to share recordings with people outside my workspace, but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Area
      options:
        - Recording / Browser Extension
        - Video Playback / Sharing
        - Workspace / Team Management
        - API
        - Self-Hosting / Deployment
        - Other
    validations:
      required: false
