kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  DATABASE_URL: "{{ .Values.sendrec.secrets.databaseUrl | b64enc }}"
  JWT_SECRET: "{{ .Values.sendrec.secrets.jwtSecret | b64enc }}"
  S3_ACCESS_KEY: "{{ .Values.sendrec.secrets.s3AccessKey | b64enc }}"
  S3_SECRET_KEY: "{{ .Values.sendrec.secrets.s3SecretKey | b64enc }}"
  GOOGLE_CLIENT_ID: "{{ .Values.sendrec.secrets.googleClientId | b64enc }}"
  GOOGLE_CLIENT_SECRET: "{{ .Values.sendrec.secrets.googleClientSecret | b64enc }}"
  MICROSOFT_CLIENT_ID: "{{ .Values.sendrec.secrets.microsoftClientId | b64enc }}"
  MICROSOFT_CLIENT_SECRET: "{{ .Values.sendrec.secrets.microsoftClientSecret | b64enc }}"
  GITHUB_SSO_CLIENT_ID: "{{ .Values.sendrec.secrets.githubSsoClientId | b64enc }}"
  GITHUB_SSO_CLIENT_SECRET: "{{ .Values.sendrec.secrets.githubSsoClientSecret | b64enc }}"
  AI_API_KEY: "{{ .Values.sendrec.secrets.aiApiKey | b64enc }}"
  LISTMONK_USERNAME: "{{ .Values.sendrec.secrets.listmonkUsername | b64enc }}"
  LISTMONK_PASSWORD: "{{ .Values.sendrec.secrets.listmonkPassword | b64enc }}"
  CREEM_API_KEY: "{{ .Values.sendrec.secrets.creemApiKey | b64enc }}"
  CREEM_WEBHOOK_SECRET: "{{ .Values.sendrec.secrets.creemWebhookSecret | b64enc }}"
type: Opaque
