{{- if not .Values.sendrec.existingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
stringData:
  DATABASE_URL: {{ .Values.sendrec.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.sendrec.secrets.jwtSecret | quote }}
  S3_ACCESS_KEY: {{ .Values.sendrec.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.sendrec.secrets.s3SecretKey | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.sendrec.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.sendrec.secrets.googleClientSecret | quote }}
  MICROSOFT_CLIENT_ID: {{ .Values.sendrec.secrets.microsoftClientId | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.sendrec.secrets.microsoftClientSecret | quote }}
  GITHUB_SSO_CLIENT_ID: {{ .Values.sendrec.secrets.githubSsoClientId | quote }}
  GITHUB_SSO_CLIENT_SECRET: {{ .Values.sendrec.secrets.githubSsoClientSecret | quote }}
  AI_API_KEY: {{ .Values.sendrec.secrets.aiApiKey | quote }}
  TRANSCRIPTION_API_KEY: {{ .Values.sendrec.secrets.transcriptionApiKey | default "" | quote }}
  LISTMONK_USER: {{ .Values.sendrec.secrets.listmonkUsername | quote }}
  LISTMONK_PASSWORD: {{ .Values.sendrec.secrets.listmonkPassword | quote }}
  SMTP_USERNAME: {{ .Values.sendrec.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.sendrec.secrets.smtpPassword | quote }}
  CREEM_API_KEY: {{ .Values.sendrec.secrets.creemApiKey | quote }}
  CREEM_WEBHOOK_SECRET: {{ .Values.sendrec.secrets.creemWebhookSecret | quote }}
type: Opaque
{{- end }}
